### ISSUE TITLE
Issue with SHA256

### ISSUE THREAD

**Issue by strinque** [D7EAD/HashPlusPlus#4]
There is a typo for SHA2_256 hashing algorithm:
```cpp
 case hashpp::ALGORITHMS::SHA2_256: {
	vSHA2_224.push_back(hashpp::SHA::SHA2_256().getHash(_data));
```

I'll provide a list of fixes soon.

**Comment by D7EAD** [comment]
Fixed the typo--assuming it is the only one. Thanks.
